sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make start-tests-upload-coverage

before_deploy:
  - docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com

deploy:
  provider: script
  script: docker push registry.heroku.com/dishonored2-power-calculator/web
  skip_cleanup: true
  on:
    branch: master