version: '3.7'
services:
  web:
    build:
      context: ./
      args:
        - GOOGLE_SITE_VERIFICATION_TOKEN
    environment:
      - GOOGLE_SITE_VERIFICATION_TOKEN
      - PORT
    ports:
      - ${PORT}:${PORT}

  dev:
    build:
      context: ./
      target: base
      args:
        - GOOGLE_SITE_VERIFICATION_TOKEN
    command: sh -c "yarn run webpack:dev-server"
    environment:
      - GOOGLE_SITE_VERIFICATION_TOKEN
      - PORT
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./html:/dishonored/html
      - ./images:/dishonored/images
      - ./manifests:/dishonored/manifests
      - ./server:/dishonored/server
      - ./src:/dishonored/src
      - ./support:/dishonored/support
      - ./webpack:/dishonored/webpack