version: "3"
services:
  web:
    build:
      context: ./
      args:
        - GOOGLE_SITE_VERIFICATION_TOKEN
    command: sh -c "npm start"
    container_name: dishonored2-web
    environment:
      - CODECOV_TOKEN
      - GOOGLE_SITE_VERIFICATION_TOKEN
      - PORT
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./html:/dishonored2-power-calculator/html
      - ./images:/dishonored2-power-calculator/images
      - ./manifests:/dishonored2-power-calculator/manifests
      - ./scripts:/dishonored2-power-calculator/scripts
      - ./server:/dishonored2-power-calculator/server
      - ./src:/dishonored2-power-calculator/src
      - ./support:/dishonored2-power-calculator/support
      - ./webpack:/dishonored2-power-calculator/webpack