version: '2'
services:
    express:
        build: ./
        image: registry.heroku.com/dishonored2-power-calculator/web:latest
        container_name: dishonored2-express
        ports:
            - 8080:8080
        volumes:
            - ./src:/src
            - /src/node_modules
