version: '3.7'
services:
  web:
    build:
      context: ./
      args:
        - GOOGLE_SITE_VERIFICATION_TOKEN
    environment:
      - GOOGLE_SITE_VERIFICATION_TOKEN
      - PORT
    ports:
      - ${PORT}:${PORT}
  dev:
    build:
      context: ./
      target: base
      args:
        - GOOGLE_SITE_VERIFICATION_TOKEN
    command: sh -c "yarn run client:dev"
    environment:
      - GOOGLE_SITE_VERIFICATION_TOKEN
      - PORT
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./public:/dishonored/public
      - ./server:/dishonored/server
      - ./src:/dishonored/src
      - ./support:/dishonored/support
      - ./index.html:/dishonored/index.html