name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    branches:
      - master
    types:
      - completed

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GOOGLE_SITE_VERIFICATION_TOKEN: cj8IJgpHPbgqe4Xs9_dAAUzO07qGnnnz5SlSN32fOnA
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: dishonored2-power-calculator
  PORT: 8080

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Trigger semantic release
        run: npx semantic-release

      - name: Login to Heroku
        run: heroku container:login

      - name: Build and push image to Heroku registry
        run: heroku container:push web --app=$HEROKU_APP_NAME --arg GOOGLE_SITE_VERIFICATION_TOKEN=$GOOGLE_SITE_VERIFICATION_TOKEN

      - name: Release image to Heroku application
        run: heroku container:release web --app=$HEROKU_APP_NAME