name: test
on: [push]
env:
  PORT: 8080
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build dev container image
        run: docker-compose build dev

      - name: Lint source files
        run: docker-compose run --rm dev yarn lint

      - name: Run tests and output coverage
        run: docker-compose run --rm --volume "$(pwd)"/jest-coverage:/dishonored/jest-coverage dev yarn test

      - name: Debugging
        run: |
          ls -al
          ls -al ./jest-coverage
          pwd

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./jest-coverage/
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false