name: test
on: [push]
env:
  PORT: 8080
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debugging
        run: |
          ls -al
          pwd
          docker --version
          docker-compose --version

      - name: Lint source files
        run: docker-compose run --rm dev yarn lint

      - name: Run tests and output coverage
        run: echo ???